language: ruby
rvm: 2.0
before_script:
  - 'cp config/config.yml.example config/config.yml'
  - psql -c "CREATE USER your_username WITH PASSWORD '';" -U postgres
  - psql -c 'create database event_girl_test' -U postgres
  - 'bundle exec rake db:migrate RAILS_ENV=test'
script: 'bundle exec rspec spec'

notifications:
  email:
    - tam.eastley@gmail.com
    - susanne.dewein@gmail.com
    - carp@hacksocke.de
    - felix@mohnert.de
