language: ruby
sudo: false
rvm:
- 2.3.1
before_script:
- cp config/config.yml.example config/config.yml
- cp config/database.yml.example config/database.yml
- psql -c "CREATE USER your_username WITH PASSWORD '';" -U postgres
- psql -c 'create database event_girl_test' -U postgres
- bundle exec rake db:migrate RAILS_ENV=test
script: bundle exec rspec spec
notifications:
  email:
  - tam.eastley@gmail.com
  - susanne.dewein@gmail.com
  - felix@mohnert.de
  webhooks:
    secure: Z52QFyfZwrQbkfYfTexO/K+CiYtik4IskhUoLZHQctraIx32F78T63kJHaQcX2Glkmarw1Ak1FJwA6vjweNv0BHT9WUQEo1rHX7am79YNmmHrbdQwgrbdoh7fVSSnaJvL8+qfirxJEhSvT3n7tg0pEeyAT41WNa05ViETCRRZxY=
deploy:
  provider: heroku
  api_key:
    secure: bpYIGNA+ovYYOXbx4tQnzqKuPDBYd92+/brHWpNDA2iOSanbxoNxzmuwsf8mmLh3OFWkcqxYuKrMuwk4vxfYBimkEQ8N170u75ZTTaC4a2nMzvNWS2aagNlHHgI1K9/u0+xk51guR5D2hzmY3SqlHM4mpgO31XeVeDdBRsFnv4I=
  app:
    master: event-girl
    refactoring/rename-app: ereignishorizont
  run:
  - rake db:migrate
  - restart
  on:
    repo: Absolventa/ereignishorizont
addons:
  postgresql: '9.3'
